/**
 * 
 */
package com.waheedtechblog;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * @author GS-0409
 *
 */

@Controller // This means that this class is a Controller
@RequestMapping(path = "/users") // This means URL's start with /users (after
									// Application path)
public class UserController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@RequestMapping(method = RequestMethod.POST) // Map ONLY GET														// Requests
	public @ResponseBody User addNewUser(@RequestBody User user) {
		// @ResponseBody means the returned String is the response, not a view
		// name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(user.getName());
		n.setEmail(user.getEmail());
		return userRepository.save(n);

	}

	@RequestMapping(method = RequestMethod.GET)
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}
